

import type { Metadata } from "next";
import Head from "next/head";
import type { WithContext, Organization } from "schema-dts";
import { Roboto, Oswald } from "next/font/google";
import DashboardLayout from "@/components/dashboard-layout/DashboardLayout";
import "./globals.scss";

const articleStructuredData: WithContext<Organization> = {
  "@context": "https://schema.org",
  "logo": "https://www.msdd.com/logo.png",
  "@type": "ProfessionalService",
  "name": "М-СДД",
  "review": {
    "@type": "Review",
    "reviewRating": {
      "@type": "Rating",
      "ratingValue": "5",
      "bestRating": "5"
    },
    "author": {
      "@type": "Person",
      "name": "Anastasiia Prots"
    }
  },
  "telephone": "+380988894542",
  "location": "Ukraine, Kiev",
  "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday"
          ],
          "opens": "9:00",
          "closes": "18:00"
        },
  ],
  "image": "/logo.png"
}

const osb = Oswald({
  subsets: ["cyrillic", "latin"],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-osb',
  style: 'normal'
})

const imb = Roboto({
  subsets: ["cyrillic", "latin"],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  variable: '--font-zen',
  style: 'normal'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
        id="faq-schema" 
        type="application/ld+json"
        dangerouslySetInnerHTML={{
        __html: JSON.stringify(articleStructuredData),
        }}/>
        <meta httpEquiv="Content-Security-Policy" />
        <meta property="og:title" content="Restaurant Troya" />
        <meta property="og:description" content="restourant" />
        <meta property="og:type" content="restourant" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="touch-icon-iphone.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="touch-icon-ipad.png"/>
        <link rel="apple-touch-icon" sizes="180x180" href="touch-icon-iphone-retina.png"/>
        <link rel="apple-touch-icon" sizes="167x167" href="touch-icon-ipad-retina.png" />
      </Head>
      <body className={`${osb.className} ${imb.className}`}>
        <DashboardLayout>
          {children}      
        </DashboardLayout>
      </body>
    </html>
  );
}
